### ISSUE TITLE
Controls in Artisan have no effect.   How to debug?

### ISSUE THREAD

**Issue by fabriziorizzo** [infinigrove/SR700-Artisan-PDServer#2]
Attempting to install on MacOS 10.12.6.  Have ./StartSAPDServer.linux.sh running, and can see console output.

Had to install to /opt/artisan/SR700, /usr/share is protected, even from root doing a mkdir... (nuts, huh...)

So, cmds install to /opt/artisan/SR700, modified all the /usr/share/ paths in the settings file to /opt/...

Artisan seems to think it's alive, but none of the buttons end up controlling the SR700.
How can I debug this?   Openroast 1.2.1 is working just fine though, so usb/serial comm drivers are okay.

./StartSAPDServer.linux.sh
Password: *********
Not starting broadcast server for localhost.
NS running on localhost:9090 (127.0.0.1)
Warning: HMAC key not set. Anyone can connect to this server!
URI = PYRO:Pyro.NameServer@localhost:9090

Ready. Object uri = PYRO:obj_127492a8d2934059a9b96fc52c395718@localhost:56608
Current Temperature: 150 idle
Current Temperature: 150 idle
Current Temperature: 150 idle
...

**Comment by AlexGS74** [comment]
In MacOs the *.py files are not executable by default. You need to make them executable by using chmod u+x *.py in the directory with the commands.
Also, check the bash shebang on the top of the files. It should point to the Python exec you are using. On my machine it needed to be updated also.
